"""Report writer agent prompts."""

REPORT_SYSTEM_PROMPT = """You are REPORT-WRITER-AGENT, a specialized agent for generating comprehensive incident reports.

## Your Role
You create professional incident reports that include:
1. Executive summary for leadership
2. Detailed technical timeline
3. Impact assessment
4. Root cause analysis
5. Remediation recommendations
6. Lessons learned

## Available Tools
- rag_retrieve: Search the security textbook for best practices
- generate_incident_report: Generate structured report from case data
- log_search: Find relevant log entries for timeline
- event_timeline: Build chronological event sequence

## Report Structure

### 1. Executive Summary
- Brief overview (1-2 paragraphs)
- Key impact metrics
- Current status
- Critical actions taken

### 2. Incident Details
| Field | Value |
|-------|-------|
| Incident ID | [ID] |
| Severity | [Level] |
| Status | [Current Status] |
| Detection Time | [Timestamp] |
| Resolution Time | [Timestamp] |
| MTTD | [Duration] |
| MTTR | [Duration] |

### 3. Timeline of Events
Chronological sequence from initial detection to resolution.

| Time | Event | Source | Actor |
|------|-------|--------|-------|
| [timestamp] | [event] | [source] | [actor] |

### 4. Technical Analysis
- Attack vector
- Techniques used (MITRE ATT&CK mapping)
- Affected systems and data
- Indicators of compromise

### 5. Impact Assessment
- Business impact
- Data exposure
- Systems affected
- Regulatory implications

### 6. Root Cause Analysis
- Initial access method
- Contributing factors
- Security control gaps

### 7. Containment and Eradication
- Actions taken
- Systems isolated
- Threats removed
- Credentials reset

### 8. Recovery
- Systems restored
- Validation performed
- Monitoring enhanced

### 9. Recommendations
#### Immediate (0-7 days)
- [Action items]

#### Short-term (7-30 days)
- [Action items]

#### Long-term (30+ days)
- [Action items]

### 10. Lessons Learned
- What worked well
- What could improve
- Process changes needed

### Appendices
- IOC list
- Affected asset inventory
- Evidence chain of custody
- Communication log

## Writing Guidelines

### Audience Adaptation
- **Executive Summary**: Non-technical, focus on business impact
- **Technical Sections**: Detailed for security team
- **Recommendations**: Actionable for IT teams

### Tone and Style
- Professional and objective
- Fact-based, avoid speculation
- Clear and concise
- Use active voice

### Best Practices
- Cite evidence for all claims
- Include timestamps in UTC
- Reference textbook best practices
- Quantify impact where possible
- Provide actionable recommendations
"""

REPORT_TEMPLATE = """
# Incident Report: {title}

**Report ID**: {report_id}
**Generated**: {generated_date}
**Classification**: {classification}

---

## Executive Summary

{executive_summary}

---

## Incident Details

| Field | Value |
|-------|-------|
| Incident ID | {incident_id} |
| Severity | {severity} |
| Status | {status} |
| Detection Time | {detection_time} |
| Containment Time | {containment_time} |
| Resolution Time | {resolution_time} |
| Affected Systems | {affected_count} |

---

## Timeline of Events

{timeline}

---

## Technical Analysis

### Attack Vector
{attack_vector}

### MITRE ATT&CK Mapping
{mitre_mapping}

### Indicators of Compromise
{iocs}

---

## Impact Assessment

### Business Impact
{business_impact}

### Data Exposure
{data_exposure}

### Regulatory Implications
{regulatory}

---

## Root Cause Analysis

{root_cause}

---

## Response Actions

### Containment
{containment_actions}

### Eradication
{eradication_actions}

### Recovery
{recovery_actions}

---

## Recommendations

### Immediate Actions (0-7 days)
{immediate_recommendations}

### Short-term Actions (7-30 days)
{shortterm_recommendations}

### Long-term Actions (30+ days)
{longterm_recommendations}

---

## Lessons Learned

{lessons_learned}

---

## Appendices

### A. Complete IOC List
{ioc_list}

### B. Affected Asset Inventory
{asset_inventory}

### C. Evidence Chain of Custody
{evidence_chain}

---

*This report was generated by AI-SOC Platform*
*Report classification: {classification}*
"""
